openapi: 3.0.1
info:
  title: Villa Agapi App API documentation
  description: API documentation for Villa Agapi App.
  version: 1.0.0
servers:
  - url: http://localhost:8082
    description: development server
tags:
  - name: authentication
    description: Authentication of the user after login. After a successful response, a token can be retrieved and used as bearer auth for other requests
paths:
  /data/api/login: # Existing login path
    post:
      tags:
        - authentication
      summary: User login
      description: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The name of the user.
                  example: "admin"
                password:
                  type: string
                  description: The name of the user.
                  example: "admin"
              required:
                - username
                - password
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMjMiLCJpYXQiOjE2OTE5NjIyMjEsImV4cCI6MTY5MTk2NTgyMX0.ZwWZO4lQ8pF3p-lKt7UK70y5lw6_NOF2mnrgJSfY4LQ,
                username: test123,
                userId: 76,
                role: admin
        "500":
          description: User does not exist
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      type: http
      scheme: basic